-- ====== 材料库 ======
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('透明质酸（玻尿酸 HA）','injectable','完全可逆（可溶解+自然代谢）','天然多糖类高分子，可抓取水分在皮下形成支撑容积，单纯物理填充，不刺激大量自体胶原新生。大分子支撑力强，小分子适合浅层细纹。','进口：乔雅登/瑞蓝/伊婉/艾莉薇/菲洛嘉；国产：润致/润百颜/海薇/芙媄登/宝尼达（长效）','大分子：鼻梁/下巴/太阳穴/鼻基底深层；中分子：苹果肌/法令纹/面颊；小分子：泪沟/唇部/眼周/水光针','眉间、鼻背浅层（血管密集，暴力注射易栓塞失明）','小分子6-12月/中分子10-18月/长效18-24月','安全性高、可溶解修复、分层适配全脸、肿胀轻微','会完全代谢需定期补打；大分子鼻梁长期注射易出现鼻梁变宽');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('羟基磷灰石 CaHA','injectable','半可逆（无溶解酶，缓慢代谢）','仿生骨骼矿物微球悬浮于凝胶载体；凝胶3-6个月吸收，微球留存刺激自体胶原再生，形成骨性支撑。','瑞得喜 Radiesse / 菲林普利','鼻梁塑形/鼻基底填充/下颌缘骨性支撑/深层法令纹','眼周、唇部、浅表细纹（质地硬，浅层注射易凹凸不平）','12-24个月','骨性支撑力强，塑形立体，适合轮廓骨性调整','不可溶解，填充过量修复难度大；质地坚硬，不适合软组织薄的眼唇');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('医用胶原蛋白','injectable','可逆（自然代谢，无专用溶解酶）','提取动物同源胶原，直接补充皮下流失胶原，兼具填充+改善肤质，质地柔软贴合薄皮肤。','双美 / 肤美达','泪沟/黑眼圈/唇部细纹/眼周浅表干纹/浅层面部凹陷','深层骨骼支撑部位（支撑力不足）','6-12个月','质地柔软，贴合薄嫩眼周皮肤，改善黑眼圈发青','支撑力弱，不适合鼻梁、下巴等需要强轮廓塑形部位');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('PLLA 聚左旋乳酸（童颜针）','injectable','半可逆（无溶解酶，缓慢代谢降解）','可降解高分子微球，不提供即时填充，刺激自身成纤维细胞分泌胶原，逐步增厚软组织，属于"胶原再生型"填充。','Sculptra 塑颜雅 / 国产童颜针','全脸容量流失/太阳穴凹陷/面颊松弛凹陷/颈部细纹','鼻梁、下巴即时塑形部位（无即刻填充效果）','2-3年（胶原缓慢自然消退）','长效改善面部衰老凹陷，自然柔和，无生硬填充感','无即时效果，需多次注射（通常3次），见效慢，不适合想立刻垫高五官者');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('PCL 聚己内酯（少女针）','injectable','半可逆（载体凝胶快速吸收，PCL微球缓慢降解，无溶解酶）','凝胶载体提供即时填充，PCL微球长期刺激胶原再生，兼具即时塑形+长效抗衰双重机制。','Ellansé 伊妍仕','鼻梁/下巴/面颊凹陷/鼻基底/下颌缘轮廓调整','眼周浅层、唇部（质地偏硬）','2-4年','既有即刻塑形效果，又能长效刺激胶原，兼顾填充与抗衰','无法溶解，填充过量修复周期长');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('PMMA 聚甲基丙烯酸甲酯（爱贝芙）','injectable','近乎永久（微球不可降解，仅载体吸收，无法溶解）','凝胶载体短期填充，PMMA硬质微球永久留存，包裹自体胶原形成永久填充层，属于"永久性异物填充"。','Bellafill 爱贝芙','重度深层法令纹/陈旧性面部凹陷/严重软组织缺损','鼻梁、眼周、唇部、浅层细纹','永久留存','一次注射长期维持，无需反复补打','永久异物留存，出现凹凸、结节只能手术取出，风险更高');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('A型肉毒毒素','injectable','完全可逆（4-6个月自然消退）','阻断神经肌肉传导（抑制乙酰胆碱释放），放松过度收缩肌肉，淡化动态皱纹、缩小肥大肌肉。','进口：保妥适/吉适/乐提葆；国产：衡力','眼周：抬头纹/眉间纹/鱼尾纹/眉提升；颌面：瘦脸咬肌/下颌缘提升/放松颏肌/改善露龈笑；身体：瘦肩/瘦小腿/腋下止汗/颈纹放松','眼轮匝肌深层、唇部肌肉过量注射（易导致面部僵硬、闭眼无力）','4-6个月','精准改善动态纹路和肌肉肥大，无异物留存','短期失效需定期补打，剂量把控不当易表情僵硬');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('自体脂肪（浅层微量注射）','injectable','半可逆（部分脂肪永久存活，剩余吸收代谢）','抽取自身腰腹/大腿脂肪提纯后注射，自体软组织无排异，存活脂肪细胞永久留存，未存活部分3-6个月吸收。','无商用品牌（取自求美者自身）','太阳穴/苹果肌/泪沟/面颊浅层凹陷','鼻梁、鼻背浅层（易栓塞、结节）','30%-60%脂肪永久存活，剩余3-6个月吸收','自身组织无排异，手感柔软','存在吸收率不定，需多次注射，有栓塞风险');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('医美可吸收埋置线材（线雕线材）','injectable','半可逆（12-24个月完全降解吸收，无溶解酶）','三类基材：PPDO（6-9月完全吸收，倒钩提拉+轻度促胶原）、PLLA线（12-18月降解，胶原刺激更强）、PCL长线（18-24月降解，支撑最久）。按形态分平滑细线、螺旋线、锯齿大V线、铃铛线，依靠倒钩锚定松弛筋膜提拉软组织。','悦升/恒生/美迪塑/MINT/玫瑰线','眼周：平滑细线改善眼尾下垂；鼻部：细线轻度抬高鼻背；面颊/法令纹：中短锯齿线提升苹果肌；下颌缘/颈部：大锯齿长线收紧双下巴','眉间、鼻背浅层（血管密集易栓塞）；唇部浅层（易表情僵硬、凸起可触及线痕）','平滑细线12个月/锯齿长线18-24个月（胶原紧致效果额外延续半年）','无外科大切口，穿刺小孔微创；线材可代谢不留永久异物；同时提拉+刺激胶原','无骨性填充支撑，不能替代假体隆鼻/垫下巴；层次不对易凹凸、异物牵拉感');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('医用固体硅胶假体','implant','不可逆（永久留存，不满意只能手术完整取出）','惰性高分子有机硅，化学性质稳定，不与人体组织融合（组织与假体间存在间隙），质地软硬可控，塑形稳定。','韩式生科/威宁/立秀/英普朗特','假体隆鼻/硅胶垫下巴/假体丰太阳穴','眼周软组织薄区域、浅表皮下植入','终身留存','塑形清晰、取出简单、价格区间广','假体与组织存在间隙，长期可能移位、透光，触感偏硬');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('膨体 ePTFE（聚四氟乙烯）','implant','不可逆（组织长入微孔，取出难度高于硅胶，需手术剥离）','多孔蜂窝结构假体，软组织可向内长入微孔，与自身组织紧密贴合，不易移位、不易透光。','射极峰 / 立秀膨体','鼻综合/鼻基底假体植入/垫下巴','浅表皮下、感染体质人群','终身留存','贴合自身组织，不易透光移位，手感自然','微孔易藏细菌，感染后取出难度大、创伤更高');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('自体软骨（耳/鼻中隔/肋软骨）','implant','不可逆（移植后软骨存活永久，修复需二次手术雕刻取出）','取自求美者自身软骨组织，同源组织无排异反应，质地柔软适合精细鼻尖塑形。耳软骨用于鼻尖修饰，鼻中隔用于鼻小柱延长，肋软骨用于全鼻综合。','无商用品牌（人体自身取材）','耳软骨：鼻尖塑形/鼻头修饰；鼻中隔：鼻小柱延长/鼻尖支撑；肋软骨：全肋鼻综合/重度鼻修复/复杂颌面凹陷填充','鼻梁单纯垫高（软骨易弯曲变形）','终身存活','完全无排异，塑形自然，适合精细鼻部修复','需要额外切口取软骨，增加手术创伤，肋软骨存在弯曲风险');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('Medpor 高密度人工骨','implant','不可逆（组织长入孔隙，需手术剥离取出）','硬质多孔医用高分子（多孔聚乙烯），骨性支撑力极强，组织可长入孔隙固定假体，适合骨骼缺损填充。','美国史赛克 Stryker','鼻基底填充/重度颌面凹陷/下巴骨骼修复','软组织浅层、眼周、唇部','终身留存','骨性支撑远超硅胶膨体，不弯曲变形','质地坚硬，触感生硬，取出创伤大');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('PEEK 3D定制人工骨','implant','不可逆（手术取出）','医用高分子（聚醚醚酮），根据个人CT数据3D打印个性化假体，完美贴合骨骼轮廓，排异率极低。','各类医用3D打印器械厂商','复杂颌面截骨修复/下巴重建/重度鼻基底骨骼缺损','浅层软组织填充','终身留存','精准贴合个人骨骼，支撑稳定，排异率极低','价格昂贵，仅用于高难度修复手术');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('玻璃酸酶（玻尿酸溶解酶）','adjuvant','1-3天分解，药剂自身快速代谢，无残留','水解透明质酸分子链，专用于玻尿酸填充过量、凹凸不平、血管栓塞急救修复。仅对透明质酸类材料生效。','医用注射用玻璃酸酶（医院院内制剂、医美专用溶解酶注射液）','全脸玻尿酸填充修复（鼻梁/泪沟/唇部/太阳穴/法令纹）','硅胶、膨体、自体软骨、CaHA、童颜针等非玻尿酸材料无法溶解；感染红肿急性期禁止注射','单次注射起效，一次性完成溶解','针对性快速修复玻尿酸填充失误，可急救栓塞风险','仅对透明质酸生效；再生填充材料、假体无效；过量注射会轻微溶解自身皮下原生玻尿酸');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('糖皮质激素局封注射液','adjuvant','局部注射后1-2周缓慢代谢，不永久留存皮下','抑制局部纤维组织过度增生，软化注射后结节、增生痘疤、瘢痕硬块。','曲安奈德注射液 / 得宝松注射液（医用院内注射制剂）','全脸增生痘疤/填充术后皮下肉芽肿/凸起瘢痕封闭治疗','面部浅表薄皮浅层注射（易造成皮肤凹陷萎缩）；孕期、糖尿病人群慎用','单次1-3个月，瘢痕严重需多次间隔注射','有效软化顽固结节、增生疤痕','浅层注射易导致局部皮肤萎缩凹陷，剂量把控要求高');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('脱氧胆酸溶脂针注射液','adjuvant','溶解脂肪细胞后药剂随身体代谢排出，无永久异物留存','破坏脂肪细胞膜，消融浅层皮下堆积脂肪，缩小局部脂肪体积。脂肪细胞凋亡后不会再生。','国内合规溶脂注射液 / 院内复合溶脂制剂','双下巴/下颌缘浅层脂肪/面颊局部赘肉美塑溶脂治疗','鼻梁、眼周、唇部软组织薄区域；深层骨骼上方；不用于重度脂肪堆积','单次疗程消融稳定，需间隔多次治疗','微创针剂溶脂，创伤远小于外科吸脂','术后肿胀疼痛明显；仅适合浅层少量脂肪；无法改善骨性宽大轮廓');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('PRP/PRF 自体血清提取制剂','adjuvant','1-3个月完全代谢，无外来异物永久留存','富集血液血小板活性生长因子，修复皮肤屏障、刺激浅层胶原，改善细纹暗沉。完全自体来源无排异。','无商用成品（求美者自体血液实验室离心提取）','全脸水光美塑/眼周细纹修复/面颊粗糙暗沉/颈部细纹注射','血液疾病、凝血功能障碍、感染期皮肤','单次改善维持1-2个月，需按疗程多次注射巩固','完全自体组织无排异，温和修复敏感受损皮肤','操作流程复杂，单次治疗成本高，无即时轮廓填充效果');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('动能素/三文鱼复合水光制剂','adjuvant','注射后1个月内完全代谢吸收','透明质酸基底搭配氨基酸、维生素、多肽，深层补水、提亮肤色、淡化干纹。仅改善肤质，无填充塑形效果。','菲洛嘉动能素 / 丝丽三文鱼水光 / 润致复合水光','全脸基础水光嫩肤/额头/面颊/颈部干燥粗糙肤质改善','急性爆痘发炎期、皮肤破损溃烂期、过敏急性期','30-45天，需定期复打','全面改善干燥、暗沉、细纹，适配所有基础肤质','仅改善肤质，无立体轮廓填充效果，代谢速度快');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('海姆泊芬静脉光敏注射剂','adjuvant','静脉输注后72小时完整代谢排出体外，无长期体内残留','富集于血管畸形内皮细胞，特定红光照射后产生活性氧封闭异常毛细血管，针对先天性血管胎记。','海姆泊芬注射液（国内唯一合规静脉光敏药剂）','面部鲜红斑痣/大面积血管性皮损光动力治疗','孕期、哺乳期、严重肝肾功能不全、光敏体质人群','单次给药配合光照完成，皮损严重需多次间隔治疗','针对先天性血管胎记、大面积红血丝皮损效果显著','给药后需严格避光72小时，易出现皮肤红肿、刺痛反应');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('果酸/水杨酸/壬二酸/复合酸/TCA焕肤制剂','topical','仅作用角质层，28天随新陈代谢完整脱落，无皮下留存','松解角质细胞粘连，疏通毛孔、加速黑色素代谢、淡化痘印、平滑粗糙肤质。不同浓度对应不同剥脱深度。','芯丝翠果酸/博乐达水杨酸/迪玛丝缇复合酸/院内调配TCA高浓度剥脱剂','额头闭口/脸颊痤疮/下巴痘印/颈部粗糙/全脸肤色暗沉焕肤','眼周、唇部黏膜、皮肤破损溃烂、急性过敏泛红、暴晒后1周内','单次焕肤改善维持1个月，周期性疗程淡化痘印色斑','无创微创，性价比高，同步改善出油、闭口、色素沉淀','术后易干燥泛红；高浓度酸存在反黑风险；敏感肌需低浓度适配');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('外用光敏凝胶（5-氨基酮戊酸 ALA）','topical','涂抹2-4小时后擦拭清除，残留成分48小时完全代谢','渗透进痤疮、浅表增生皮损，特定光源照射产生活性氧，杀灭痤疮丙酸杆菌、抑制皮肤异常增生。','医用光动力外用 ALA 凝胶','中重度炎性痤疮/浅表皮肤增生修复','眼内黏膜、唇部薄嫩黏膜、大面积破损溃烂皮肤','单次涂抹配合光照完成，炎症痤疮需3-5次疗程','针对性改善反复炎症痘痘，无抗生素耐药问题','光照过程刺痛明显；治疗后需严格避光3天；短期皮肤干燥脱皮');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('基础物理治疗配套外用制剂','topical','仅皮肤表层涂抹，清水可清洗，不渗透皮下长期留存','导电凝胶传导仪器能量、冷敷面膜补水舒缓、辅助活性成分浅层渗透，降低光电仪器对皮肤的刺激。','医美专用医用冷敷贴/射频导电凝胶/院内舒缓导入原液','全脸/颈部基础皮肤护理（红蓝光/无创射频/微电流/药物导入/冷喷）','对精华凝胶成分过敏、皮肤大面积破溃患者','单次治疗即时舒缓补水，无长期塑形抗衰效果','降低光电物理仪器刺激，术后快速舒缓泛红干敏','仅辅助护理，无独立改善色斑、细纹、轮廓功效');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('射频/聚焦超声专用治疗探头','device','仅治疗时贴合皮肤表层，不植入皮下，治疗后回收更换','传导射频/超声热能至真皮、筋膜层（SMAS），收紧松弛软组织、刺激胶原再生。单探头限定固定发数。','热玛吉原厂射频治疗探头/超声炮配套超声换能探头/台式多极射频耗材头','热玛吉全脸/颈部紧致；超声炮下颌缘/中面部提拉；额头/眼周/面颊/下颌/颈部抗衰紧致','眼内眼球、骨骼表层过薄皮肤、面部金属植入物上方','一次性消耗品，单探头限定固定发数，单次治疗使用一支','精准分层传递热能，紧致抗衰效果稳定','一次性耗材成本高，探头发数用尽必须更换，无法重复使用');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('微针类射频/点阵耗材针头','device','穿刺表皮后即刻拔出，针头不留在皮肤内，一次性使用废弃','微针穿刺表皮直达真皮层，同步传递射频热能，刺激胶原再生+机械性皮肤重建，改善毛孔、痘坑、细纹。','黄金微针原厂射频微针阵列/医用一次性滚针微针套件','黄金微针：毛孔/痘坑/眼周细纹/下颌松弛；全脸微针导入营养精华','急性爆痘炎症期、皮肤溃烂、血管畸形皮损','单人次一次性针头，治疗后直接丢弃，不可重复消毒复用','精准控制穿刺深度，射频同步紧致，修复痘坑毛孔效果优于单纯点阵激光','破皮微创，术后有结痂恢复期，敏感肌恢复期泛红明显');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('各类激光配套治疗手具/脱毛激光耗材头','device','仅光源发射接触皮肤表面，无穿刺植入，无耗材留存人体','发射特定波长激光，靶向击碎黑色素（皮秒/调Q）、毛细血管（染料激光）、毛囊黑色素（半导体脱毛激光），实现选择性光热作用。','皮秒原厂治疗手具/点阵激光光学耗材/半导体脱毛激光探头','皮秒祛斑洗纹身/点阵激光修复痘坑疤痕/唇毛发际线络腮胡脱毛；全脸色斑细纹色素沉淀改善','眼球、深色胎记易灼伤区域、暴晒后色素活跃皮肤','仪器手具可重复使用，仅配套冷却保护耗材单次更换','波长细分针对性强，祛斑、脱毛、疤痕修复分设备精准改善','能量把控不当易出现反黑、色素脱失，术后严格防晒要求高');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('头面部射频光纤消融针（光纤溶脂耗材）','device','术中穿刺皮下脂肪层，治疗结束完整抽出光纤，无耗材留在体内','细光纤传导射频热能进入皮下脂肪层，消融浅层皮下脂肪细胞，同步收紧皮下筋膜软组织，实现溶脂+紧致双重效果。','医用光纤溶脂专用射频穿刺光纤套件','额部/颞部/面颊/下颌/颈部浅层脂肪消融收紧','鼻梁、眼周薄软组织、深层骨骼上方脂肪；不适用重度骨性宽大轮廓改善','光纤为一次性无菌耗材，单人单次使用后废弃','微创针孔溶脂，创伤远低于外科开刀吸脂，同步紧致皮肤不松弛','仅能消融浅层少量脂肪；下颌骨骨性宽大无改善作用；术后肿胀7-14天');
INSERT INTO materials (name,category,reversible,principle,brands,sites,contraindications,duration,pros,cons) VALUES ('等离子/微波/红蓝光物理治疗配套耗材','device','体外仪器耗材，仅贴合皮肤表层，无穿刺无植入，可重复清洁使用','等离子焕肤打磨表皮、微波抗炎紧致、红蓝光抑制痤疮杆菌（蓝光杀菌/红光抗炎）、冷喷舒缓镇静。均为体外物理能量，无化学药剂留存。','医用等离子嫩肤仪耗材/皮肤科LED光疗设备套件','全脸痤疮炎症/毛孔粗糙/敏感肌泛红舒缓；额头/面颊/颈部基础物理护理','皮肤恶性增生皮损；金属植入区域微波治疗慎用','仪器探头可重复消毒使用，仅配套过滤棉、缓冲膜为单次消耗品','几乎无创无破皮，适合敏感肌日常维稳抗炎','仅改善轻度肤质炎症，无深层抗衰、填充塑形功效');

-- ====== 手术项目 ======
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('eye-1','eye','眼部区域','重睑成形术（双眼皮）','surgery','通过全切法、埋线法或三点式在上睑形成重睑褶皱。被称为"Asian blepharoplasty"，是东亚地区最常见的医美手术。','永久','¥3,000-30,000','{"术后7天严重肿胀","形态不满意需二次修复","修复价格远高于初次"}','[{"name":"无需植入物","brands":["可配合眶隔脂肪释放"]}]','{"physical":"术后7天严重肿胀期，3个月形态逐步稳定；术后需忌口及避免眼部摩擦2周","expectation":"追求\"欧式大宽双\"易显假，自然款更耐看；埋线法约3-5年可能松脱","cost":"初次手术¥3,000-15,000，修复手术¥20,000-50,000+，差异巨大"}','{"aesthetic":"双眼皮手术在西方医学文献中被称作\"Asian blepharoplasty\"，被认为是亚洲人种面部特征改造的代表性手术，折射出东西方审美权力的不对等。","autonomy":"多数求美者将单眼皮视为\"无神\"的自我认知，手术成为重塑自信的途径；但也有人术后怀念原本的特色单眼皮。","social":"短视频和社交媒体持续强化\"大眼=精致\"的单一审美标准，削弱了东亚原生眼型的美感多样性。","refs":["Stanford Medicine - Asian Blepharoplasty","DOI: 10.1055/s-0040-1717147"]}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('eye-2','eye','眼部区域','内眦赘皮矫正（开眼角）','surgery','通过内眦成形术或外眦成形术切除内眼角多余皮肤，增大眼裂长度。','永久','¥2,000-12,000','{"内眼角瘢痕增生","眼距过近破坏面部比例"}','[{"name":"无需植入物","brands":[]}]','{"physical":"术后内眼角有瘢痕风险，约3-6个月软化；初期有牵拉感","expectation":"开眼角过度会导致眼距过近，破坏三庭五眼的面部黄金比例","cost":"初次¥2,000-8,000，瘢痕修复¥5,000-15,000"}','{"aesthetic":"内眦赘皮（蒙古褶）是蒙古人种的眼部特征，开眼角手术本质上是消除这一种族特征，向\"大眼无褶\"的西方审美靠拢。","autonomy":"部分求美者仅因他人评价\"眼睛小\"就选择开眼角，而非基于自身审美需求。","social":"开眼角+双眼皮已成为东亚医美\"套餐标配\"，个体差异性被标准化手术模板取代。","refs":["ASPS 3D Animations"]}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('eye-3','eye','眼部区域','下睑眼袋整形术','surgery','结膜入路（内切）或皮肤入路（外切）去除/重置眶隔脂肪，改善下睑袋状隆起。可配合泪沟填充。','5-10年','¥5,000-25,000','{"脂肪去除过量导致眼眶凹陷","外切法留疤痕","下睑外翻"}','[{"name":"自体眶隔脂肪","brands":["可配合玻尿酸/胶原蛋白填充泪沟"]}]','{"physical":"外切法恢复期2-3周，淤青约10天消退；内切法恢复快但适应症有限","expectation":"脂肪去除过量会导致下睑凹陷，反而更显老；保留适量脂肪更自然","cost":"初次¥5,000-15,000，修复+脂肪回填¥20,000-50,000"}','{"aesthetic":"眼袋在当代社会被标签化为\"显老\"\"疲惫\"的体征，但医学上它是正常的眶隔脂肪垫结构，其突出程度受遗传因素影响远大于年龄。","autonomy":"去除眼袋常伴随着找回\"精神感\"的心理诉求，但过度去除带来的凹陷反而加速衰老外观。","social":"职场文化中将\"疲惫面容\"等同于\"竞争力下降\"，间接推动中年群体选择眼袋手术。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('eye-4','eye','眼部区域','肉毒素眼周除皱','injection','通过注射A型肉毒素阻断神经肌肉传导，松弛眼周表情肌，改善动态纹（鱼尾纹、眉间纹、抬头纹）。','4-6个月','¥800-5,000/次','{"表情僵硬","眉下垂","上睑下垂","不对称"}','[{"name":"A型肉毒素","brands":["保妥适Botox","衡力","吉适Dysport","乐提葆Letybo"]}]','{"physical":"注射3天后淤青基本消退，1周见效，2周达峰值；几乎无恢复期","expectation":"剂量过大导致\"扑克脸\"，微笑时眼周无动态纹显得不自然","cost":"每年需2-3次补打，年支出¥2,400-15,000；长期累积成本超过单次外科手术"}','{"aesthetic":"肉毒素的可逆性使其成为年轻人\"试错\"医美的首选，它重新定义了\"抗衰\"——不是消除衰老，而是控制表情本身。","autonomy":"可逆性给予求美者更高的身体自主权：不满意则等待代谢，不留下永久改变。这种低风险特性降低了医美的心理门槛。","social":"疫情期间\"Zoom脸\"焦虑推动了眼周肉毒素的需求激增——人们在视频会议中长时间注视自己的面部，放大了对动态纹的不满。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('eye-5','eye','眼部区域','玻尿酸泪沟填充','injection','使用小分子玻尿酸在泪沟区域（眶下凹陷）进行浅层填充，改善眼袋下方的凹陷阴影。','6-12个月','¥1,500-8,000/次','{"丁达尔现象（皮肤泛蓝）","血管栓塞","不平整"}','[{"name":"小分子玻尿酸","brands":["乔雅登Juvéderm","瑞蓝Restylane","润百颜","润致"]}]','{"physical":"注射后轻微肿胀2-3天，即刻见效；泪沟区域皮肤薄，技术要求高","expectation":"短期平整效果好，但6个月后逐渐吸收需补打；长期成本累计高于眼袋手术","cost":"每年1-2次补打，年支出¥3,000-16,000；5年成本¥15,000-80,000 vs 眼袋手术一次¥5,000-25,000"}','{"aesthetic":"泪沟填充反映了\"眼下平整无阴影\"成为年轻感的标志——但正常的眶下凹陷本是面部立体感的来源之一。","autonomy":"玻尿酸可被溶解酶快速清除，这种\"可逆性\"为求美者提供了心理安全网。","social":"美妆教程中大量\"遮泪沟\"技巧的存在，说明泪沟焦虑已渗透至日常化妆行为。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('eye-6','eye','眼部区域','眼周光电抗衰','dermatology','使用点阵激光、黄金微针、热玛吉或皮秒激光改善眼周细纹、松弛和肤质。','6-12个月','¥2,000-15,000/次','{"术后结痂5-7天","敏感肌持续干燥泛红","色素沉着"}','[{"name":"光电设备","brands":["热玛吉Thermage","皮秒PicoSure","黄金微针","点阵激光"]}]','{"physical":"术后结痂期约5-7天，期间不能化妆；敏感肌可能持续干燥泛红2-4周","expectation":"需多次疗程（3-5次）才有明显效果，单次改善有限","cost":"全套疗程¥6,000-50,000，需每年维护"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('nose-1','nose','鼻部区域','假体隆鼻术','surgery','通过鼻腔内切口植入假体材料（硅胶或膨体）以增高鼻梁、改善鼻型。','永久','¥5,000-50,000','{"硅胶：移位/透光/触感偏硬","膨体：微孔易藏细菌/感染后取出难度大"}','[{"name":"固体硅胶","brands":["韩式生科","威宁","立秀","英普朗特"]},{"name":"膨体ePTFE","brands":["射极峰","立秀膨体"]}]','{"physical":"术后1月明显肿胀期，3-6个月形态稳定；硅胶触感偏硬，膨体更自然但取出创伤大","expectation":"硅胶假体可能透光（阳光下可见假体轮廓）；膨体感染后治疗周期极长（数月抗生素+取出）","cost":"硅胶假体¥5,000-20,000；膨体¥15,000-50,000；感染修复费用可能数倍于初次"}','{"aesthetic":"高鼻梁在社会审美中与\"精致\"\"立体\"\"洋气\"绑定，原生矮鼻被贴\"土气\"标签——这种审美建构深深植根于西方面部特征的审美霸权。","autonomy":"选择硅胶还是膨体，反映不同个体对风险的取舍：硅胶易取出但可能透光，膨体自然但感染后代价大。","social":"中国已成为全球鼻整形手术量最高的国家之一，\"隆鼻\"在年轻女性中的讨论热度接近日常美容话题。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('nose-2','nose','鼻部区域','鼻尖成形术（自体软骨）','surgery','取用自体耳软骨、鼻中隔软骨或肋软骨雕刻后移植至鼻尖，塑造鼻尖形态和延长鼻小柱。','永久（软骨存活后）','¥15,000-80,000','{"取肋软骨胸口留疤","软骨弯曲变形","吸收率不确定"}','[{"name":"自体软骨","brands":["耳软骨（鼻尖修饰）","鼻中隔软骨（鼻小柱延长）","肋软骨（全鼻综合）"]}]','{"physical":"取肋软骨者胸口有2-3cm疤痕，术后胸部疼痛1-2周；鼻部肿胀3-6个月","expectation":"软骨存在10-20%吸收率，最终形态需等待1年才能确定；肋软骨存在弯曲变形风险","cost":"耳软骨鼻尖¥15,000-30,000；肋软骨全鼻综合¥30,000-150,000"}','{"aesthetic":"自体软骨代表\"用自身组织修复自身\"的理念，某种程度上抵制了工业化假体的异物感——是身体自主权在医美中的一种体现。","autonomy":"但取肋软骨意味着在身体另一部位制造创伤，这种\"拆东墙补西墙\"的选择反映了容貌改造的深层代价。","social":"肋软骨鼻综合被称为\"鼻整形天花板\"，其高价和技术门槛使之成为高端医美的身份象征。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('nose-3','nose','鼻部区域','玻尿酸隆鼻','injection','注射大分子玻尿酸于鼻梁、鼻尖等部位，即刻增高鼻梁、改善鼻型。','10-18个月','¥2,000-10,000/次','{"血管栓塞（严重可致失明）","鼻梁扩散变宽","长期反复注射总价高"}','[{"name":"大分子玻尿酸","brands":["乔雅登","瑞蓝","艾莉薇","润百颜"]}]','{"physical":"注射后轻微红肿2-3天，即刻见效无恢复期；但1年后鼻梁逐渐扩散变宽","expectation":"适合轻度修饰，不适合大幅增高；反复在同一部位注射会累积扩散效应","cost":"每年¥2,000-10,000，5年¥10,000-50,000，可能超过单次假体手术"}','{"aesthetic":"玻尿酸隆鼻的\"可逆性\"使其成为年轻人鼻部医美的首选试水方式——但可逆不等于无风险，血管栓塞可致失明。","autonomy":"可溶解酶提供\"后悔药\"，但这种可逆性可能促使求美者在未充分评估风险的情况下冲动决策。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('nose-4','nose','鼻部区域','CaHA羟基磷灰石鼻部填充','injection','使用羟基磷灰石微球（CaHA）填充鼻梁和鼻基底，提供骨性支撑力。','12-24个月','¥3,000-12,000/次','{"无法溶解","填充过量只能等待代谢","质地硬不适合眼唇"}','[{"name":"羟基磷灰石CaHA","brands":["瑞得喜Radiesse","菲林普利"]}]','{"physical":"骨性支撑力强，塑形立体；但质地偏硬，填充过量无法溶解只能等待多年代谢","expectation":"适合需要骨性支撑的部位（鼻梁、鼻基底），不适合软组织部","cost":"比玻尿酸持久但价格更高，且不可逆（无法溶解）"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('nose-5','nose','鼻部区域','鼻部点阵激光/光子','dermatology','使用点阵激光或强脉冲光（IPL）改善鼻部痘坑、黑头、毛孔粗大及红血丝问题。','6-12个月','¥800-5,000/次','{"术后结痂","需严格防晒","色素沉着风险"}','[{"name":"光电设备","brands":["点阵激光","光子嫩肤IPL","皮秒激光"]}]','{"physical":"术后结痂3-7天，期间不能化妆；需严格防晒1个月防反黑"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('lip-1','lip','唇/口周区域','厚唇改薄手术','surgery','通过唇内侧切口去除部分黏膜和肌肉组织，将过厚的唇部修薄。','永久','¥3,000-12,000','{"唇部麻木1-2个月","线条僵硬","自然微笑时违和"}','[{"name":"无需植入物","brands":[]}]','{"physical":"术后1周进食时有刺痛感，嘴唇麻木感持续1-2个月；唇内侧疤痕隐蔽","expectation":"术后唇形可能过于僵硬，自然微笑时缺乏动态美感","cost":"修复手术（如过度切除后补填）价格可能数倍于初次"}','{"aesthetic":"东亚文化传统中偏好薄唇，但当下受韩流和西方审美影响，饱满M唇逐渐流行——唇部审美经历了从\"薄=精致\"到\"饱满=性感\"的转向。","autonomy":"唇部是最高频的动态表情器官，任何永久性改变都可能影响微笑、说话等日常表达的舒适度。","social":"社交平台上的\"微笑唇\"模板普及，唇形的好看标准被不断窄化。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('lip-2','lip','唇/口周区域','薄唇增厚术（M唇成形）','surgery','通过唇珠塑造和唇弓加深技术，塑造当下流行的饱满M型唇形。','永久','¥5,000-20,000','{"线条僵硬","唇部敏感度下降","可能不自然"}','[{"name":"无需植入物","brands":[]}]','{"physical":"术后肿胀2周，进食不便；唇部触觉敏感度可能永久下降","expectation":"静态好看但动态违和——微笑时唇形变化不自然","cost":"¥5,000-20,000，修复费用更高"}','{"aesthetic":"当下偏爱饱满M唇，但几十年前流行薄唇——唇形审美具有明显的时代性和文化建构性。东亚传统一度排斥厚唇，而欧美文化欣赏饱满唇形。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('lip-3','lip','唇/口周区域','玻尿酸丰唇','injection','注射小分子玻尿酸增加唇部容积，改善唇形、唇珠和唇纹。','6-8个月','¥1,500-6,000/次','{"注射后2天明显肿胀","盲目追求厚度导致不协调","不对称"}','[{"name":"小分子玻尿酸","brands":["乔雅登","瑞蓝","伊婉","润百颜"]}]','{"physical":"注射后2天肿胀明显（预期内的\"香肠嘴\"阶段），1周消肿后形态自然","expectation":"常见误区是追求过厚效果，与五官不协调；唇部玻尿酸代谢较快","cost":"每6-8个月需补打，年支出¥3,000-12,000"}','{"aesthetic":"玻尿酸丰唇给了求美者\"试用\"饱满唇形的机会——作为可逆项目，它降低了唇形审美的转换成本，也加速了审美潮流的更迭。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('lip-4','lip','唇/口周区域','口周肉毒素','injection','在口周注射肉毒素以改善露龈笑、放松颏肌（下巴肌肉）、淡化木偶纹。','4-6个月','¥500-3,000/次','{"剂量把控难","过量导致闭唇无力","流口水"}','[{"name":"A型肉毒素","brands":["保妥适","衡力","吉适","乐提葆"]}]','{"physical":"几乎无恢复期，3天后起效；但剂量把控至关重要","expectation":"过量注射导致闭唇无力、喝水漏液、发音受影响","cost":"每年2-3次¥1,000-9,000"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('lip-5','lip','唇/口周区域','唇周光电/刷酸','dermatology','使用光电设备或化学剥脱改善唇周暗沉、脱毛、红血丝和细纹。','视疗程而定','¥500-4,000/次','{"唇周皮肤脆弱易脱皮反黑","需严格防晒"}','[{"name":"光电/化学剥脱","brands":["皮秒激光","光子嫩肤","果酸/水杨酸"]}]','{"physical":"唇周皮肤薄且敏感，术后易脱皮、反黑；需特别注意防晒和保湿","expectation":"暗沉改善需多次疗程，单次效果有限"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('jaw-1','jaw','下颌/颌面区域','假体隆颏术（垫下巴）','surgery','通过口腔内或下巴下方切口植入假体，延长或突出下巴，改善面下三分之一比例。','永久','¥8,000-60,000','{"假体过长导致说话咬合不自然","异物感","感染风险"}','[{"name":"硅胶/膨体/Medpor/PEEK","brands":["韩式生科","射极峰","史赛克Medpor","3D打印PEEK"]}]','{"physical":"术后下巴麻木1-3个月，逐渐恢复；口腔内切口不影响外观","expectation":"假体过长或过大导致咬合不适和说话不自然","cost":"硅胶¥8,000-20,000；PEEK 3D定制¥30,000-60,000"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('jaw-2','jaw','下颌/颌面区域','下颌角肥大截骨','surgery','通过口内切口切除部分下颌角骨质，缩小下颌宽度，改变方脸轮廓。四级手术，全麻下进行。','永久','¥30,000-100,000','{"神经损伤（下唇麻木）","骨不连","面部下垂","严重出血"}','[{"name":"无需植入物","brands":[]}]','{"physical":"全麻手术，住院3-7天；面部严重肿胀持续1-2个月，完全消肿需3-6个月","expectation":"下颌角切除过多会导致面部支撑不足，加速面部下垂；神经麻木可能是永久性的","cost":"¥30,000-100,000（四级手术定价），修复手术更加昂贵且复杂"}','{"aesthetic":"下颌角截骨是东亚地区特有的高频颌面手术——西方审美偏好清晰的下颌角（Jawline），而东亚追求\"V脸\"无角化。方圆脸被贴上\"脸大\"\"臃肿\"标签。","autonomy":"截骨是不可逆的四级手术，其风险-收益比远超微创项目。选择截骨的求美者通常经历了长期的容貌焦虑累积。","social":"韩国\"V脸\"审美的全球化输出，使得下颌角截骨成为跨国医美旅游的热门项目。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('jaw-3','jaw','下颌/颌面区域','肉毒素瘦脸（咬肌）','injection','在咬肌部位注射肉毒素，使咬肌萎缩变小，达到瘦脸效果。是目前最受欢迎的微创医美项目之一。','4-6个月','¥800-4,000/次','{"面部松弛（咬肌萎缩后）","蛙腮（不均匀萎缩）","咀嚼无力"}','[{"name":"A型肉毒素","brands":["保妥适","衡力"]}]','{"physical":"注射后2周开始见效，1个月达峰值；咀嚼硬物时感觉咬肌无力","expectation":"咬肌萎缩后皮肤可能松弛——尤其是年龄较大、皮肤弹性差的人群","cost":"每年2-3次¥1,600-12,000；长期累积成本高但风险极低"}','{"aesthetic":"咬肌注射的普及使得\"瘦脸\"从外科手术下沉为日常医美维护——但咬肌本是咀嚼功能所需肌肉，将其萎缩的行为模糊了医美与身体功能之间的界限。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('jaw-4','jaw','下颌/颌面区域','下颌缘锯齿线埋线','injection','使用PPDO/PLLA/PCL大V线沿下颌缘埋入，通过锯齿钩挂提拉松弛软组织，重塑下颌线。','18-24个月','¥3,000-15,000/次','{"牵拉酸胀2周","线体可触","不对称","线头顶出"}','[{"name":"PPDO/PLLA/PCL线材","brands":["悦升","恒生","美迪塑","MINT"]}]','{"physical":"术后持续牵拉酸胀感约2周，不能做大幅度表情；线体可被触摸到","expectation":"改善轻度松弛，但不能替代拉皮手术；线吸收后提拉效果逐渐消失","cost":"¥3,000-15,000/次，维持18-24个月"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('jaw-5','jaw','下颌/颌面区域','超声炮（下颌）','dermatology','使用高强度聚焦超声（HIFU）精准加热SMAS筋膜层，收紧下颌松弛软组织。','1-1.5年','¥3,000-12,000/次','{"面部凹陷（能量过高）","神经损伤","效果不明显"}','[{"name":"超声设备","brands":["超声炮（国产）","美版超声刀Ultherapy"]}]','{"physical":"术中酸胀感明显，术后持续紧绷感；1月内不能大力揉搓面部","expectation":"效果渐进（1-3个月显现），单次效果有限，需配合其他项目"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('jaw-6','jaw','下颌/颌面区域','热玛吉（下颌/全脸）','dermatology','使用射频技术加热真皮层和皮下组织，刺激胶原蛋白再生，紧致下颌及面部皮肤。','1-2年','¥8,000-25,000/次','{"术后干燥泛红","能量不足导致无效","能量过高可致烫伤"}','[{"name":"射频设备","brands":["热玛吉Thermage"]}]','{"physical":"术后干燥泛红1-2周，即刻有紧致感但最终效果需等3-6个月胶原再生","expectation":"紧致效果而非提升效果——不能替代拉皮手术","cost":"¥8,000-25,000/次，每1-2年需重复"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('temple-1','temple','太阳穴/面颊区域','颞部假体填充（丰太阳穴）','surgery','通过头皮内切口植入硅胶或膨体假体，填充凹陷的太阳穴区域。','永久','¥8,000-30,000','{"头皮切口疤痕","触摸有硬物感","假体移位"}','[{"name":"硅胶/膨体","brands":["韩式生科","射极峰"]}]','{"physical":"头皮切口隐蔽，但触摸时有硬物感；术后肿胀1-2周","expectation":"太阳穴填充可改善面部上宽下窄的比例，但假体可能移位","cost":"¥8,000-30,000一次性支出"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('temple-2','temple','太阳穴/面颊区域','玻尿酸填充太阳穴/苹果肌','injection','注射中大分子玻尿酸填充太阳穴凹陷和苹果肌，即刻恢复面部饱满感。','10-18个月','¥2,000-10,000/次','{"过度填充出现\"充气感假面\"","血管栓塞","肿胀1周"}','[{"name":"中/大分子玻尿酸","brands":["乔雅登","瑞蓝","艾莉薇","伊婉"]}]','{"physical":"肿胀持续约1周；过量填充导致不自然的\"充气感假面\"","expectation":"追求过度饱满会导致面部比例失调，自然的轻度填充更耐看","cost":"每年¥2,000-10,000，长期成本累积可观"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('temple-3','temple','太阳穴/面颊区域','PLLA童颜针（全脸凹陷）','injection','注射聚左旋乳酸（PLLA）微球，刺激自体胶原蛋白分泌，渐进性填充面部凹陷。','2-3年','¥5,000-20,000/次（3次一疗程）','{"无即时填充效果","需3次注射","结节风险"}','[{"name":"PLLA聚左旋乳酸","brands":["Sculptra塑颜雅","国产童颜针"]}]','{"physical":"无即时效果！注射后需要等待2-3个月自身胶原逐渐增生才能看到变化","expectation":"求美者常因\"打完没变化\"误以为无效而追加注射——需要充分理解其滞后性","cost":"一疗程3次¥15,000-60,000，可维持2-3年"}','{"aesthetic":"童颜针的\"无即时效果\"本质上是反消费主义的——它拒绝即刻满足，要求求美者等待身体自己的生产节奏。但这种\"慢\"在医美快消文化中恰恰成了推广障碍。"}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('temple-4','temple','太阳穴/面颊区域','PCL少女针（面颊）','injection','注射聚己内酯（PCL）微球凝胶，即刻填充并长效刺激胶原，兼顾即时与长效。','2-4年','¥8,000-20,000/次','{"无法溶解","填充过量修复周期长","价格高"}','[{"name":"PCL聚己内酯","brands":["Ellansé伊妍仕"]}]','{"physical":"即刻填充效果+长期胶原刺激，注射后轻微肿胀数天","expectation":"兼顾了玻尿酸的即时性和童颜针的长效性，但无法溶解是最大风险","cost":"¥8,000-20,000/次，维持2-4年，年均成本可能低于玻尿酸"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('temple-5','temple','太阳穴/面颊区域','热玛吉全脸紧致','dermatology','使用射频加热真皮层，刺激胶原蛋白再生，全面改善面部松弛和细纹。','1-2年','¥8,000-25,000/次','{"术后干燥泛红1-2周","能量不当可致烫伤"}','[{"name":"射频设备","brands":["热玛吉Thermage"]}]','{"physical":"术后皮肤干燥泛红1-2周，需大量补水；3-6个月后效果最明显","expectation":"紧致松弛而非消除皱纹——需配合其他项目才能全面改善"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('temple-6','temple','太阳穴/面颊区域','中面部锯齿线埋线','injection','使用PPDO/PLLA锯齿线提升苹果肌、淡化法令纹。','18-24个月','¥3,000-12,000/次','{"牵拉感","线体可触","维持时间有限"}','[{"name":"PPDO/PLLA锯齿线","brands":["悦升","恒生","美迪塑","MINT"]}]','{"physical":"术后持续牵拉感约2周；线体在某些角度可被触摸到","expectation":"适合轻中度松弛，重度松弛仍需手术"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('neck-1','neck','颈部区域','颈部拉皮除皱','surgery','通过耳后和发际线内切口提紧颈部皮肤和颈阔肌，去除多余皮肤，改善颈部松弛。','5-10年','¥20,000-80,000','{"创伤大","疤痕隐蔽但存在","恢复期2个月","面部紧绷感"}','[{"name":"无需植入物","brands":[]}]','{"physical":"术后明显肿胀2-4周，完全恢复需2个月；耳后疤痕隐蔽但终生存在","expectation":"改善明显但创伤大，适合严重颈部松弛的中老年人群","cost":"¥20,000-80,000，单次手术维持5-10年"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('neck-2','neck','颈部区域','颈纹玻尿酸填充','injection','将小分子玻尿酸注射入颈部横向纹路中，抚平颈纹。','6-12个月','¥1,500-5,000/次','{"皮肤薄易出现凸起条索","不平整","效果有限"}','[{"name":"小分子玻尿酸","brands":["乔雅登","瑞蓝","润百颜"]}]','{"physical":"颈部皮肤极薄，注射后可能出现凸起条索（玻尿酸线性凸起）","expectation":"对浅表细纹有一定效果，但深层横纹改善有限；需多次治疗","cost":"每6-12个月¥1,500-5,000，长期累积成本高"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('neck-3','neck','颈部区域','颈纹肉毒素注射','injection','在颈阔肌条索和颈横纹处注射肉毒素，放松肌肉改善动态颈纹。','4-6个月','¥800-3,000/次','{"吞咽不适","颈部无力","发音受影响"}','[{"name":"A型肉毒素","brands":["保妥适","衡力"]}]','{"physical":"注射后可能出现短暂吞咽不适；效果在1-2周内显现","expectation":"改善动态颈纹（肌肉收缩引起），对静态纹效果有限","cost":"每年2-3次¥1,600-9,000"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('neck-4','neck','颈部区域','热玛吉颈部紧致','dermatology','使用射频探头加热颈部皮肤和皮下组织，刺激胶原新生收紧颈部皮肤。','1-2年','¥5,000-15,000/次','{"颈部皮肤薄需控制能量","干燥泛红","效果渐进"}','[{"name":"射频设备","brands":["热玛吉Thermage"]}]','{"physical":"颈部皮肤更薄，治疗时热感更明显；术后干燥持续1-2周","expectation":"紧致效果温和渐进，适合轻度松弛预防；严重松弛需手术"}','{}');
INSERT INTO procedures (id,region,region_name,name,category,description,duration,price_range,risks,materials,feedback,humanities) VALUES ('neck-5','neck','颈部区域','黄金微针（颈纹）','dermatology','微针穿刺+射频能量同步释放，刺激颈部皮肤胶原再生，改善颈纹质地。','1-1.5年','¥2,000-8,000/次','{"微创破皮","结痂3-5天","需多次疗程"}','[{"name":"微针射频设备","brands":["黄金微针"]}]','{"physical":"术后微小结痂3-5天，期间不能涂抹颈部护肤品；需3-5次疗程","expectation":"改善颈纹质感和紧致度，但颈纹深度不能完全消除"}','{}');

-- ====== 皮肤问题 ======
INSERT INTO skin_conditions (id,name,problem,cause,treatments,feedback) VALUES ('wrinkles','皱纹（动态纹+静态纹）','额头纹、眉间纹、鱼尾纹、法令纹、木偶纹','动态纹由表情肌反复收缩形成；静态纹由皮肤胶原蛋白和弹性纤维流失、光老化叠加形成。','[{"name":"肉毒素除皱","category":"injection","desc":"针对动态纹，阻断神经肌肉传导","duration":"4-6个月","price":"¥800-5,000"},{"name":"玻尿酸填充","category":"injection","desc":"针对静态纹，物理填平凹陷","duration":"6-18个月","price":"¥1,500-8,000"},{"name":"线雕提升","category":"injection","desc":"锯齿线提拉松弛，改善法令纹","duration":"12-24个月","price":"¥3,000-15,000"},{"name":"热玛吉/超声炮","category":"dermatology","desc":"加热真皮层/筋膜层，紧致皮肤","duration":"1-2年","price":"¥8,000-25,000"},{"name":"黄金微针","category":"dermatology","desc":"微针+射频改善细纹","duration":"1-1.5年","price":"¥2,000-8,000"},{"name":"点阵激光","category":"dermatology","desc":"剥脱/非剥脱，重建胶原","duration":"1-2年","price":"¥2,000-10,000"}]','{"physical":"肉毒素3天见效，表情僵硬风险；激光术后结痂7-10天","expectation":"动态纹可大幅改善，静态纹只能淡化不能完全消除","cost":"注射类年均¥2,000-15,000；光电类年均¥5,000-25,000"}');
INSERT INTO skin_conditions (id,name,problem,cause,treatments,feedback) VALUES ('acne','痤疮/痘痘','面颊和下巴区域的炎性痤疮、闭口粉刺、痘坑痘印','皮脂分泌过剩+毛囊口角化异常+痤疮丙酸杆菌增殖+炎症反应。受激素水平、饮食、压力等多因素影响。','[{"name":"光动力治疗","category":"dermatology","desc":"ALA光敏凝胶+光照杀灭痤疮杆菌","duration":"3-5次一疗程","price":"¥1,500-5,000/次"},{"name":"红蓝光治疗","category":"dermatology","desc":"无创杀菌消炎","duration":"需多次","price":"¥300-1,000/次"},{"name":"化学剥脱（刷酸）","category":"dermatology","desc":"果酸/水杨酸疏通毛孔","duration":"每月1次","price":"¥500-2,000/次"},{"name":"黄金微针射频","category":"dermatology","desc":"改善痘坑+控油","duration":"3-5次","price":"¥2,000-8,000/次"},{"name":"CO2点阵激光","category":"dermatology","desc":"痘坑修复最佳方案","duration":"1-3次","price":"¥3,000-10,000/次"}]','{"physical":"光动力治疗时刺痛明显，术后需严格避光3天；刷酸后干燥泛红脱皮；CO2激光恢复期1-2周","expectation":"痘坑只能改善不能完全消除；严重痘坑需多种方案联合治疗","cost":"完整治疗方案¥5,000-50,000+，取决于严重程度"}');
INSERT INTO skin_conditions (id,name,problem,cause,treatments,feedback) VALUES ('spots','色斑/色素沉淀','颧骨褐青色痣（太田痣）、雀斑、黄褐斑、晒斑、痘印色素','紫外线照射（光老化）、激素波动（黄褐斑）、遗传（雀斑）、炎症后色素沉着（PIH）、年龄增长。','[{"name":"皮秒/超皮秒激光","category":"dermatology","desc":"光机械效应击碎色素颗粒","duration":"3-5次","price":"¥2,000-8,000/次"},{"name":"调Q激光","category":"dermatology","desc":"深层色斑爆破","duration":"3-5次","price":"¥1,500-5,000/次"},{"name":"光子嫩肤IPL","category":"dermatology","desc":"浅层色斑+肤色不均","duration":"5-10次","price":"¥800-3,000/次"},{"name":"化学剥脱","category":"dermatology","desc":"表皮色斑淡化","duration":"周期性","price":"¥500-2,000/次"}]','{"physical":"激光术后色斑区域会暂时加深（结痂/色沉），约1-2周脱落；严格防晒至关重要","expectation":"黄褐斑极易复发，受紫外线/激素/情绪多因素影响；雀斑易复发需定期维护","cost":"全套祛斑方案¥5,000-50,000+，且需终身防晒维护"}');
INSERT INTO skin_conditions (id,name,problem,cause,treatments,feedback) VALUES ('pores','毛孔粗大/肤质粗糙','T区及面颊毛孔粗大、皮肤粗糙、暗沉无光泽','皮脂分泌旺盛撑大毛孔、皮肤老化致毛孔周围支撑组织减少、清洁不当、紫外线光老化。','[{"name":"黄金微针射频","category":"dermatology","desc":"精准控制穿刺+射频紧致","duration":"3-5次","price":"¥2,000-8,000/次"},{"name":"非剥脱点阵激光","category":"dermatology","desc":"改善毛孔+恢复期短","duration":"3-5次","price":"¥1,500-5,000/次"},{"name":"刷酸焕肤","category":"dermatology","desc":"疏通毛孔+加速代谢","duration":"每月1次","price":"¥500-2,000/次"},{"name":"水光针","category":"injection","desc":"深层补水改善肤质","duration":"30-45天","price":"¥800-3,000/次"}]','{"physical":"黄金微针术后结痂3-5天；刷酸后干燥泛红；水光针注射后微小针眼1-2天消退","expectation":"毛孔只能缩小不能完全消失；需长期维护管理","cost":"年均¥5,000-30,000，取决于项目组合"}');
INSERT INTO skin_conditions (id,name,problem,cause,treatments,feedback) VALUES ('darkcircles','黑眼圈','眼下暗沉发青/发褐/凹陷，分为血管型、色素型、结构型三类','血管型（眼周皮肤薄可见血管发青）、色素型（黑色素沉淀发褐）、结构型（泪沟凹陷阴影）。','[{"name":"胶原蛋白填充","category":"injection","desc":"血管型最佳，遮盖青色","duration":"6-12个月","price":"¥2,000-8,000/次"},{"name":"玻尿酸填充","category":"injection","desc":"结构型泪沟填充","duration":"6-12个月","price":"¥1,500-8,000/次"},{"name":"皮秒激光","category":"dermatology","desc":"色素型黑眼圈淡化","duration":"3-5次","price":"¥1,500-5,000/次"},{"name":"手术联合治疗","category":"surgery","desc":"结构型需眼袋手术+泪沟填充","duration":"5-10年","price":"¥10,000-30,000"}]','{"physical":"胶原蛋白填充后青眼圈即刻改善（白色覆盖青色）；玻尿酸泪沟填充有丁达尔泛蓝风险","expectation":"结构型黑眼圈仅靠填充效果有限，需联合手术才能根本改善","cost":"注射维护年均¥3,000-16,000；手术一次性¥10,000-30,000"}');
INSERT INTO skin_conditions (id,name,problem,cause,treatments,feedback) VALUES ('necklines','颈纹','颈部横纹、颈阔肌条索、颈部皮肤松弛','颈部皮肤极薄且皮脂腺少（天然缺乏保湿）、长期低头（手机/电脑）、光老化、自然老化胶原流失。','[{"name":"玻尿酸填充","category":"injection","desc":"填充横向颈纹","duration":"6-12个月","price":"¥1,500-5,000/次"},{"name":"肉毒素注射","category":"injection","desc":"放松颈阔肌改善动态纹","duration":"4-6个月","price":"¥800-3,000/次"},{"name":"热玛吉颈部","category":"dermatology","desc":"紧致颈部皮肤","duration":"1-2年","price":"¥5,000-15,000/次"},{"name":"黄金微针","category":"dermatology","desc":"改善颈纹质地","duration":"3-5次","price":"¥2,000-8,000/次"}]','{"physical":"颈部皮肤薄，玻尿酸注射易出现凸起条索；肉毒素可能导致吞咽不适","expectation":"颈纹只能改善不能消失；预防（防晒+保湿+减少低头）比治疗更重要","cost":"年均¥3,000-20,000，取决于方案组合"}');

-- ====== 思辨文章 ======
INSERT INTO humanities_essays (id,num,title,description,themes) VALUES ('essay-1','01','可逆微创 vs 永久外科 — 身体改造的风险取舍','可逆注射/线雕类项目的低试错成本迎合了"先体验、不满意可恢复"的消费心态；而永久外科手术代表对长期固定容貌的接受和不可逆风险的承担。二者的选择本质上是不同个体对"自我身体控制权"的观念差异。年轻人偏好可逆（肉毒素、玻尿酸），中年人面临更显著的衰老时更倾向选择永久手术。可逆性降低了医美的心理门槛，但也可能导致冲动决策——"大不了溶解"的思维绕过了对风险本身的充分评估。','{"可逆性","风险","身体控制权","年龄差异"}');
INSERT INTO humanities_essays (id,num,title,description,themes) VALUES ('essay-2','02','标准化大众审美与原生面部差异化冲突','医美行业在全球范围内输出了一套统一的审美模板：高鼻梁、大双眼皮、尖下巴、饱满面中、清晰下颌线。原生五官的特色——单眼皮、宽鼻梁、方圆脸、薄唇——被视作需要修正的"瑕疵"。医美技术既是美化工具，也在客观上缩小了人类的容貌多样性。当越来越多的人通过手术趋向同一审美模板，街头巷尾的面孔越来越相似，"美"的定义本身被窄化了。双眼皮手术（Asian blepharoplasty）作为东亚最高频的医美手术，是种族特征改造最具代表性的案例。','{"审美标准化","容貌多样性","种族特征","社会审美"}');
INSERT INTO humanities_essays (id,num,title,description,themes) VALUES ('essay-3','03','医美、容貌焦虑与身体自主的辩证关系','医美与容貌焦虑的关系是双面的。负面来看，短视频、广告和网红文化不断放大面部"缺陷"，制造持续升级的容貌内卷，使原本正常的面部特征成为需要"修复"的问题。正面来看，医美确实给容貌自卑人群提供了调整自我的渠道——对于因先天或后天因素导致面部差异而遭受社会歧视的人，医美技术是重要的心理和社会支持工具。关键在于区分"发自内心的自我完善需求"和"被外界标准裹挟的盲目改造"。社会压力（同辈对比、职场竞争、婚恋市场）的介入使这一区分变得困难。','{"容貌焦虑","身体自主","自我完善","社会压力"}');
INSERT INTO humanities_essays (id,num,title,description,themes) VALUES ('essay-4','04','不同年龄、经济水平人群的医美选择差异','医美选择存在明显的阶层区分。学生群体以低价可逆项目为主（肉毒素、玻尿酸小部位、皮肤管理），以试错和轻度改善为目的。中青年经济稳定群体可能接受鼻综合、面部拉皮等永久手术。高消费阶层可触及3D定制PEEK植入、全肋鼻综合、四级颌面截骨等高端项目。医美不仅是容貌改造，也成为一种社会阶层的消费符号——选择什么项目、在什么机构、用什么材料，透露着经济实力和社交圈层的信息。这种阶层差异也引发了对"美的公平性"的讨论。','{"经济阶层","消费差异","美的公平性","社会符号"}');

-- ====== 部位人文观察 ======
INSERT INTO humanities_regions (region,aesthetic,autonomy,social_context) VALUES ('眼部','大众追求"大双眼/无眼袋/平整泪沟"，弱化单眼皮特色；早年流行细长丹凤眼，如今追求平行大双——眼部审美经历了从"古典东方美"到"西式大眼"的转向。','年轻人选肉毒素试错（低风险+可逆），中年人倾向外科永久改善（眼袋手术/提眉）——不同生命阶段的自主选择策略截然不同。','短视频放大"无神眼""显老眼袋"负面标签；疫情期间Zoom会议加剧了眼周医美需求。');
INSERT INTO humanities_regions (region,aesthetic,autonomy,social_context) VALUES ('鼻部','高鼻梁在社会审美中与"精致立体""洋气"强绑定，原生宽鼻/矮鼻被贴上"土气"标签——这种审美建构植根于西方面部特征的审美霸权。','未成年人倾向注射尝试（玻尿酸隆鼻），经济独立者承担永久手术风险（假体/肋软骨）。','广告持续强化"鼻子决定颜值"的叙事，推动统一容貌内卷。中国已成为全球鼻整形手术量最高的国家之一。');
INSERT INTO humanities_regions (region,aesthetic,autonomy,social_context) VALUES ('唇/口周','唇部审美经历了时代性转向——数十年前流行薄唇，当下偏爱饱满M唇；东亚传统一度排斥厚唇，而欧美文化欣赏饱满唇形。','唇部作为高动态表情器官，多数人害怕永久手术破坏自然微笑，优先选择可逆注射。','网红"微笑唇"模板普及，原生唇形被认为不够精致；唇部审美窄化加剧。');
INSERT INTO humanities_regions (region,aesthetic,autonomy,social_context) VALUES ('下颌/颌面','东亚社会统一追求"尖窄翘下巴+清晰下颌线"，弱化方圆脸的自然特色——"V脸"审美与西方偏好的清晰Jawline形成文化对比。','颌面高风险永久手术（截骨、四级手术）仅少数人接受；多数人止步于注射和光电仪器改善。','方圆脸被广泛贴上"脸大""臃肿"标签，社交媒体上的小脸滤镜加剧了下颌改造需求。韩国V脸审美的全球化输出推动了跨国医美旅游。');
INSERT INTO humanities_regions (region,aesthetic,autonomy,social_context) VALUES ('太阳穴/面颊','"饱满无凹陷=年轻"的等式深入人心，原生颞部凹陷和面颊消瘦被归为"衰老缺陷"——但医学上面部凹陷受骨骼结构和遗传因素主导。','惧怕开刀疤痕者全部优先选择注射填充（玻尿酸/童颜针/少女针），排斥传统拉皮手术。','年龄焦虑推动中青年通过填充掩盖自然衰老迹象——"抗衰"需求的起龄不断提前。');
INSERT INTO humanities_regions (region,aesthetic,autonomy,social_context) VALUES ('颈部','颈部长期以来被审美所忽略，但近年来颈部衰老也开始被视为颜值"扣分点"——审美标准从面部向下延伸至颈部。','颈部暴露在外且皮肤薄，多数人排斥开刀疤痕，优先选择光电仪器和注射治疗。','智能手机时代"低头族"颈纹年轻化趋势明显，镜头近距离拍摄放大了颈纹在社会互动中的可见度。');